### ISSUE TITLE
Heroku deploy down

### ISSUE THREAD

**Issue by tyleryy** [lukeren314/ZotDegree#10]
Hi, I don't know if you are still active on this repo, but could you bring this website back? It says it is down on Heroku or something.

**Comment by lukeren314** [comment]
Hi Tyler,
Unfortunately I'm no longer maintaining this website (I've moved onto other things), and the free hosting provider I used (Heroku) recently shut down their free hosting plan.

If you would like to host it yourself, all of the code should is here in this repo, but I do not have the time to give instructions on how to do so. If I were to redo this project, I would rewrite the code to update an external database with all of the crawled data, and then serve the API using serverless functions so that the app could run on a cloud-distributed hosting platform with an unlimited free plan such as Netlify or Vercel. Just some ideas in case someone down the line would like to pick up this project where I left off.

Sorry for the inconvenience,
Luke Ren, ZotDegree creator
